### ISSUE TITLE
权限部分功能待完善

### ISSUE THREAD

**Issue by EUForest** [jzero-io/jzero-admin#4]
挺期待这个项目能健康的更新，Rt，子菜单添加那块按钮提交没有做判断，导致无法提交子菜单，我本地以及修改了

**Comment by jaronnie** [comment]
哈喽，很开心能有伙伴看到这个项目。当前还在逐步适配功能，我也是在工作之余慢慢改进这个项目，会一直更新，但可能不会太快。另外后端是基于我开源的 jzero 框架，请问你有看到这个项目嘛

**Comment by jaronnie** [comment]
如果你也有兴趣的话，可以一起参与下哈

**Comment by jaronnie** [comment]
该问题已修复，但是还有未完成的部分哈权限这块

**Comment by EUForest** [comment]
可以的，请留下您的联络方式，我联系你，我这边可以共同与你维护。

**Comment by jaronnie** [comment]
我的微信: jaronnie
